[versions]
minecraft = "1.20.1"
minecraftForge = "1.20.1-47.4.0"
parchment = "2023.09.03"

# Dependencies
gtceu = "1.6.4"
emi = "1.1.10"
jei = "15.20.0.121"
webpImageio = "0.1.6"

[plugins]
modDevGradle = { id = "net.neoforged.moddev.legacyforge", version = "2.0.78" }
